import Link from "next/link";
import type { Metadata } from "next";
import { brand } from "@/lib/brand";

const APP_URL = process.env.APP_URL ?? "https://app.claimtive.com";

export const metadata: Metadata = {
  title: `${brand.name} — AI Revenue Recovery for Specialty Practices`,
  description:
    "Claimtive automates EDI 835 remittance processing and AI-drafts payer-specific appeal letters the same day denials arrive. Flat monthly pricing built for independent practices."
};

const STATS = [
  { num: "12%", label: "Average claim denial rate for specialty practices in 2025 — up from 9% in 2022" },
  { num: "$25K+", label: "Estimated annual revenue loss per provider from unresolved denials" },
  { num: "84%", label: "Of physician practices say their billing and collections systems need an upgrade" }
];

const STEPS = [
  {
    n: 1,
    title: "Connect",
    body: "Upload EDI 835 remittance files or connect via your existing clearinghouse. No EMR changes required."
  },
  {
    n: 2,
    title: "Parse",
    body: "AI extracts denial reason codes (CARC/RARC), payer, claim amounts, and root causes automatically."
  },
  {
    n: 3,
    title: "Draft",
    body: "LLM generates payer-specific appeal letters the same day the denial arrives — your biller reviews and sends."
  },
  {
    n: 4,
    title: "Track",
    body: "Dashboard surfaces denial trends by payer, code, and provider so you can see revenue recovered over time."
  }
];

const FEATURES = [
  {
    icon: "▤",
    title: "835 Remittance Auto-Parsing",
    body: "Ingest EDI 835 files from any clearinghouse and extract denial data in seconds, not hours."
  },
  {
    icon: "✦",
    title: "AI Appeal Drafting",
    body: "Payer-specific appeal letters generated by an LLM trained on CARC/RARC denial codes and contract terms."
  },
  {
    icon: "◈",
    title: "Pre-submission Denial Scoring",
    body: "Flag claims likely to be denied before they go out, based on payer + procedure + diagnosis patterns. (Q4 2026)"
  },
  {
    icon: "▦",
    title: "Underpayment Detection",
    body: "Compare actual reimbursements against your contract terms and peer benchmarks to recover left-behind revenue."
  }
];

const PLANS = [
  {
    name: "Solo",
    sub: "1 provider",
    price: "$150–200",
    highlight: false,
    features: [
      { label: "835 remittance auto-parsing", included: true },
      { label: "AI appeal letter drafting", included: true },
      { label: "Denial trend dashboard", included: true },
      { label: "Underpayment benchmarking", included: false },
      { label: "Pre-submission denial scoring", included: false }
    ]
  },
  {
    name: "Group",
    sub: "2–4 providers",
    price: "$300–600",
    highlight: true,
    features: [
      { label: "835 remittance auto-parsing", included: true },
      { label: "AI appeal letter drafting", included: true },
      { label: "Denial trend dashboard", included: true },
      { label: "Underpayment benchmarking", included: true },
      { label: "Pre-submission denial scoring", included: true }
    ]
  }
];

export default function HomePage() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      {/* NAV */}
      <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/90 backdrop-blur-sm">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link href="/" className="text-xl font-bold tracking-tight text-brand-700">
            claim<span className="text-brand-500">tive</span>
          </Link>
          <nav className="flex items-center gap-6">
            <a href="#how-it-works" className="hidden text-sm font-medium text-slate-600 hover:text-brand-600 sm:block">
              How it works
            </a>
            <a href="#pricing" className="hidden text-sm font-medium text-slate-600 hover:text-brand-600 sm:block">
              Pricing
            </a>
            <a href={`${APP_URL}/login`} className="text-sm font-medium text-slate-600 hover:text-brand-600">
              Sign in
            </a>
            <a href={`${APP_URL}/signup`} className="btn-primary text-sm">
              Get started
            </a>
          </nav>
        </div>
      </header>

      {/* HERO */}
      <section className="mx-auto max-w-6xl px-6 pb-20 pt-20 text-center">
        <h1 className="mx-auto max-w-3xl text-4xl font-bold leading-tight tracking-tight text-slate-900 sm:text-5xl">
          Stop writing off denied claims.{" "}
          <span className="text-brand-600">Start recovering revenue.</span>
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg text-slate-500 leading-relaxed">
          Claimtive parses your 835 remittance files and uses AI to draft payer-specific appeal letters the same day denials arrive — without touching your EMR. Built for independent specialty practices with 1–5 providers.
        </p>
        <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
          <a href={`${APP_URL}/signup`} className="btn-primary px-8 py-3 text-base">
            Start free pilot
          </a>
          <a href="#how-it-works" className="btn-secondary px-8 py-3 text-base">
            See how it works
          </a>
        </div>
        <p className="mt-4 text-xs text-slate-400">
          No EMR changes · No IT project · 15-minute setup
        </p>
      </section>

      {/* STATS */}
      <section className="border-y border-slate-100 bg-slate-50">
        <div className="mx-auto max-w-6xl px-6 py-12 grid grid-cols-1 gap-8 sm:grid-cols-3">
          {STATS.map((s) => (
            <div key={s.num} className="flex items-start gap-4">
              <div className="shrink-0 text-3xl font-bold text-brand-600">{s.num}</div>
              <p className="text-sm text-slate-500 leading-relaxed">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* THE PROBLEM */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-brand-500 mb-3">The problem</p>
            <h2 className="text-3xl font-bold text-slate-900 leading-tight">
              Enterprise RCM tools weren&apos;t built for your practice.
            </h2>
            <p className="mt-4 text-slate-500 leading-relaxed">
              Waystar, AKASA, and R1 RCM all require health system IT departments and six-figure minimums. Independent practices with 1–5 providers are left managing denials manually — the billing person appeals by hand and silently writes off anything that looks hard.
            </p>
            <p className="mt-4 text-slate-500 leading-relaxed">
              The average denial rate for specialty practices hit 12% in 2025. That&apos;s revenue you earned, sitting in payer accounts because you don&apos;t have the staff to fight for it.
            </p>
          </div>
          <div className="space-y-3">
            {[
              "Remittance files manually reconciled — hours per week",
              "Appeal letters written from scratch, payer by payer",
              "Denials older than 90 days silently written off",
              "No visibility into which payers deny most by code",
              "No pre-submission warning before claims go out"
            ].map((item) => (
              <div
                key={item}
                className="flex items-start gap-3 rounded-lg border border-slate-200 bg-white px-4 py-3 shadow-sm"
              >
                <span className="mt-0.5 font-bold text-red-400">✕</span>
                <span className="text-sm text-slate-600">{item}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how-it-works" className="bg-slate-50 border-y border-slate-100">
        <div className="mx-auto max-w-6xl px-6 py-20">
          <div className="text-center mb-14">
            <p className="text-xs font-bold uppercase tracking-widest text-brand-500 mb-3">How it works</p>
            <h2 className="text-3xl font-bold text-slate-900">Same-day denial response, automatically.</h2>
          </div>
          <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">
            {STEPS.map((step) => (
              <div key={step.n}>
                <div className="flex h-10 w-10 items-center justify-center rounded-full bg-brand-600 text-white font-bold text-sm mb-4">
                  {step.n}
                </div>
                <h3 className="font-bold text-slate-900 mb-2">{step.title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{step.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="text-center mb-14">
          <p className="text-xs font-bold uppercase tracking-widest text-brand-500 mb-3">The product</p>
          <h2 className="text-3xl font-bold text-slate-900">
            Everything your billing team needs. Nothing they don&apos;t.
          </h2>
        </div>
        <div className="grid gap-6 sm:grid-cols-2">
          {FEATURES.map((f) => (
            <div key={f.title} className="card p-6">
              <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-brand-50 text-brand-600 text-lg">
                {f.icon}
              </div>
              <h3 className="font-semibold text-slate-900 mb-1">{f.title}</h3>
              <p className="text-sm text-slate-500 leading-relaxed">{f.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="bg-slate-50 border-y border-slate-100">
        <div className="mx-auto max-w-6xl px-6 py-20">
          <div className="text-center mb-4">
            <p className="text-xs font-bold uppercase tracking-widest text-brand-500 mb-3">Pricing</p>
            <h2 className="text-3xl font-bold text-slate-900">
              Flat monthly fee. No percentage of collections.
            </h2>
            <p className="mt-3 text-slate-500 max-w-xl mx-auto">
              A 2-provider practice paying $400/month needs to recover roughly one additional claim per month to break even. The average spine/pain claim is $800–2,000+.
            </p>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 max-w-2xl mx-auto">
            {PLANS.map((plan) => (
              <div
                key={plan.name}
                className={`rounded-xl border p-8 ${
                  plan.highlight
                    ? "border-brand-500 bg-brand-600 text-white shadow-lg"
                    : "border-slate-200 bg-white"
                }`}
              >
                {plan.highlight && (
                  <div className="mb-3 inline-flex rounded-full bg-white/20 px-2 py-0.5 text-xs font-bold text-white">
                    Most popular
                  </div>
                )}
                <h3 className={`text-xl font-bold ${plan.highlight ? "text-white" : "text-slate-900"}`}>
                  {plan.name}
                </h3>
                <p className={`text-sm ${plan.highlight ? "text-brand-200" : "text-slate-500"}`}>{plan.sub}</p>
                <div className={`mt-4 text-4xl font-bold ${plan.highlight ? "text-white" : "text-slate-900"}`}>
                  {plan.price}
                  <span className={`text-base font-normal ${plan.highlight ? "text-brand-200" : "text-slate-400"}`}>
                    /mo
                  </span>
                </div>
                <ul className="mt-6 space-y-3">
                  {plan.features.map((f) => (
                    <li key={f.label} className="flex items-center gap-3 text-sm">
                      <span
                        className={
                          f.included
                            ? plan.highlight ? "text-white" : "text-brand-500"
                            : plan.highlight ? "text-brand-300" : "text-slate-300"
                        }
                      >
                        {f.included ? "✓" : "—"}
                      </span>
                      <span
                        className={
                          plan.highlight
                            ? f.included ? "text-white" : "text-brand-300"
                            : f.included ? "text-slate-700" : "text-slate-400"
                        }
                      >
                        {f.label}
                      </span>
                    </li>
                  ))}
                </ul>
                <div className="mt-8">
                  <a
                    href={`${APP_URL}/signup`}
                    className={`block w-full rounded-lg py-2.5 text-center text-sm font-semibold transition ${
                      plan.highlight
                        ? "bg-white text-brand-700 hover:bg-brand-50"
                        : "btn-primary"
                    }`}
                  >
                    Start free pilot
                  </a>
                </div>
              </div>
            ))}
          </div>
          <p className="mt-6 text-center text-xs text-slate-400">
            5+ providers?{" "}
            <a href={`${APP_URL}/signup`} className="text-brand-600 hover:underline">
              Talk to us
            </a>{" "}
            about volume pricing.{" "}
            Billing companies serving multiple practices —{" "}
            <a href={`${APP_URL}/signup`} className="text-brand-600 hover:underline">
              contact us
            </a>{" "}
            for white-label pricing.
          </p>
        </div>
      </section>

      {/* PILOT CTA */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="rounded-2xl bg-brand-600 px-8 py-14 text-center">
          <h2 className="text-3xl font-bold text-white">Pilot cohort now open.</h2>
          <p className="mt-4 text-brand-200 max-w-xl mx-auto text-lg leading-relaxed">
            We&apos;re onboarding a small group of independent specialty practices for our founding cohort. Setup takes 15 minutes. No EMR changes. No IT team required.
          </p>
          <div className="mt-8">
            <a
              href={`${APP_URL}/signup`}
              className="inline-flex items-center justify-center rounded-lg bg-white px-8 py-3 text-base font-semibold text-brand-700 transition hover:bg-brand-50"
            >
              Apply for early access
            </a>
          </div>
          <p className="mt-4 text-xs text-brand-300">
            Limited spots · Pain management · Spine · Orthopedics · PT/OT
          </p>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-slate-100">
        <div className="mx-auto max-w-6xl px-6 py-10 flex flex-col items-center justify-between gap-4 sm:flex-row">
          <div className="text-lg font-bold text-brand-700">
            claim<span className="text-brand-500">tive</span>
          </div>
          <p className="text-xs text-slate-400 text-center">
            AI-powered revenue recovery for independent specialty practices
          </p>
          <div className="flex items-center gap-6 text-xs text-slate-500">
            <a href={`${APP_URL}/login`} className="hover:text-brand-600">Sign in</a>
            <a href={`${APP_URL}/signup`} className="hover:text-brand-600">Get started</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
